---
os: linux
dist: xenial

language: python
python:
  - 3.8

install:
  # the PyPI coordinates will change once we get dedicated entitlements
  - >
    pip install -e .[dev]

script:
  # style enforcement
  - python -m black --check --diff --color .
  - python -m isort --profile black --check --diff .
  - python -m flake8 .
  # static typing
  - python -m mypy src